@startuml
class System
{
    createTournament()
}

class Tournament
{
    String tournamentDescription;
    int tournamentDateStart;
    int tournamentDateEnd;

    createTournament()
}

class Registrations
{
    String nameOfTeam;
    String[] nameOfPlayers;

    receiveRegistrations()
}

class Matches
{
    int matchGoalScores;

    addTeams()
    scheduleMatches()
}

class MatchResults
{
    int registerResult;
    int tournamentGoalScore;

    recordMatchResults()
}

class FileIO
{
ReadData()
SaveData()
}

System <|-- Tournament
System <|-- Registrations
System <|-- Matches
System <|-- MatchResults
Registrations <|-- FileIO
Main <|-- System

@enduml