@startuml

!pragma layout smetana

class Main
{
static main(String[] args)
}

class System
{
    +runTournament()
}

class Tournament
{
    -String tournamentDescription;
    -int tournamentDateStart;
    -int tournamentDateEnd;

    +createTournament()
}

class TextUI
{
+ ArrayList<String> getPlayerNames()
}

class Team
{
    +ArrayList<String> players
+ ArrayList<String> getPlayer()
}

class Registration
{
    -String nameOfTeam;
    -String[] nameOfPlayers;

    +receiveRegistrations()
}

class Match
{
    -int matchGoalScores;
    - int registerResult
    - int tournamentGoalScore;

    +addTeams()
    +scheduleMatches()
    +recordMatchResults()
}

class FileIO
{
    +inputData()
    +readResult()
    +readData()
    +saveData()
}
System *-- TextUI: has-a
TextUI *-- Team: has-a
System *-- Tournament: has-a
System *-- Registrations: has-a
System *-- "7"Matches: has-a
System *-- FileIO: has-a
Registrations <|-- FileIO:has-a
Main *-- System: has-a
TextUI *-- Registration
System *-- Match

@enduml